POST http://localhost:3001/api/auth/register
Content-Type: application/json

{
  "name": "Abbas kasturi",
  "email": "22641a6776@vaagdevi.edu.in",
  "password": "12345"
}

###

POST http://localhost:3001/api/auth/register
Content-Type: application/json

{
  "name": "Lavan",
  "email": "22641a6710@vaagdevi.edu.in",
  "password": "12345"
}

###

POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
  "email": "22641a6776@vaagdevi.edu.in",
  "password": "12345"
}

###

POST http://localhost:3001/api/products
Content-Type: multipart/form-data; boundary=----WebAppBoundary
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU0ODExODMwLCJleHAiOjE3NTc0MDM4MzB9.mx01UVkVtPDMYvxlQSO6BMRjJyhonxbkJy56nOACix4

------WebAppBoundary
Content-Disposition: form-data; name="category"

Laptop
------WebAppBoundary
Content-Disposition: form-data; name="name"

ASUS ROG Strix Scar 17

------WebAppBoundary
Content-Disposition: form-data; name="rentalCostPerDay"

40
------WebAppBoundary
Content-Disposition: form-data; name="collectionPlace"

Vaagdevi College main gate 
------WebAppBoundary
Content-Disposition: form-data; name="contactPhoneNumber"

9492781864
------WebAppBoundary
Content-Disposition: form-data; name="proofRequired"

College ID copy and Aadhar Card copy
------WebAppBoundary
Content-Disposition: form-data; name="securityDeposit"

2000
------WebAppBoundary
Content-Disposition: form-data; name="model"

AMD Ryzen 9 7945HX
------WebAppBoundary
Content-Disposition: form-data; name="ram"

32 GB
------WebAppBoundary
Content-Disposition: form-data; name="rom"

2 TB SSD
------WebAppBoundary
Content-Disposition: form-data; name="processor"

Ryzen 9
------WebAppBoundary
# IMPORTANT: You MUST replace the path below with a real path to an image on your computer.
Content-Disposition: form-data; name="imageUrl"; filename="hp-envy.jpg"
Content-Type: image/jpeg

< C:\ResumeFolder\resume folder\vaagdeviProjectimages\asus-5.jpeg
------WebAppBoundary--



### 

POST http://localhost:3001/api/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU0NTcwMzQyLCJleHAiOjE3NTcxNjIzNDJ9.I9Md-D-c6U03dkkO_8l3JdQuqgq1Z7_NeoC-J1ZvZyY
Content-Type: multipart/form-data; boundary=----WebAppBoundary

------WebAppBoundary
Content-Disposition: form-data; name="category"

Camera
------WebAppBoundary
Content-Disposition: form-data; name="name"

Fujifilm Instax Mini 11
------WebAppBoundary
Content-Disposition: form-data; name="rentalCostPerDay"

35
------WebAppBoundary
Content-Disposition: form-data; name="collectionPlace"

collect at d-block
------WebAppBoundary
Content-Disposition: form-data; name="contactPhoneNumber"

9123456789
------WebAppBoundary
Content-Disposition: form-data; name="proofRequired"

Student ID card copy with aadhar card copy 
------WebAppBoundary
Content-Disposition: form-data; name="securityDeposit"

1000
------WebAppBoundary
Content-Disposition: form-data; name="model"

Instant
------WebAppBoundary
Content-Disposition: form-data; name="storage"

Instax film pack included
------WebAppBoundary
Content-Disposition: form-data; name="imageUrl"; filename="canon200d.jpg"
Content-Type: image/jpeg

< C:\ResumeFolder\resume folder\vaagdeviProjectimages\cam-5.webp
------WebAppBoundary--


### 

### Create a New Drafter
POST http://localhost:3001/api/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU0NTcwMzQyLCJleHAiOjE3NTcxNjIzNDJ9.I9Md-D-c6U03dkkO_8l3JdQuqgq1Z7_NeoC-J1ZvZyY
Content-Type: multipart/form-data; boundary=----WebAppBoundary

------WebAppBoundary
Content-Disposition: form-data; name="category"

Drafter
------WebAppBoundary
Content-Disposition: form-data; name="name"

Flexible Arm Drafter
------WebAppBoundary
Content-Disposition: form-data; name="rentalCostPerDay"

29
------WebAppBoundary
Content-Disposition: form-data; name="collectionPlace"

Stationery Shop
------WebAppBoundary
Content-Disposition: form-data; name="contactPhoneNumber"

9492781864
------WebAppBoundary
Content-Disposition: form-data; name="proofRequired"

College ID Card copy
------WebAppBoundary
Content-Disposition: form-data; name="securityDeposit"

200
------WebAppBoundary
Content-Disposition: form-data; name="model"

Kohinoor Flexi
------WebAppBoundary
# IMPORTANT: You MUST replace the path below with a real path to an image on your computer.
Content-Disposition: form-data; name="imageUrl"; filename="drafter.jpg"
Content-Type: image/jpeg

< C:\ResumeFolder\resume folder\vaagdeviProjectimages\d-5.jpg
------WebAppBoundary--



### =================================
### POST A NEW BIKE
### =================================

### Create a New Bike
POST http://localhost:3001/api/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU0NTcwMzQyLCJleHAiOjE3NTcxNjIzNDJ9.I9Md-D-c6U03dkkO_8l3JdQuqgq1Z7_NeoC-J1ZvZyY
Content-Type: multipart/form-data; boundary=----WebAppBoundary

------WebAppBoundary
Content-Disposition: form-data; name="category"

Bike
------WebAppBoundary
Content-Disposition: form-data; name="name"

pulsar
------WebAppBoundary
Content-Disposition: form-data; name="rentalCostPerDay"

100
------WebAppBoundary
Content-Disposition: form-data; name="collectionPlace"

college main gate
------WebAppBoundary
Content-Disposition: form-data; name="contactPhoneNumber"

9492781864
------WebAppBoundary
Content-Disposition: form-data; name="proofRequired"

College ID Card copy and aadhar card copy 
------WebAppBoundary
Content-Disposition: form-data; name="securityDeposit"

2000
------WebAppBoundary
Content-Disposition: form-data; name="condition"

Good
------WebAppBoundary
Content-Disposition: form-data; name="model"

pulsar 220
------WebAppBoundary
Content-Disposition: form-data; name="onRoadSpeed"

38 km/h
------WebAppBoundary
# IMPORTANT: You MUST replace the path below with a real path to an image on your computer.
Content-Disposition: form-data; name="imageUrl"; filename="bike.jpg"
Content-Type: image/jpeg

< C:\ResumeFolder\resume folder\vaagdeviProjectimages\bike-5.bmp
------WebAppBoundary--



### =================================
### POST A NEW GATEBOOK
### =================================

### Create a New Gatebook
POST http://localhost:3001/api/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU0NTcwMzQyLCJleHAiOjE3NTcxNjIzNDJ9.I9Md-D-c6U03dkkO_8l3JdQuqgq1Z7_NeoC-J1ZvZyY
Content-Type: multipart/form-data; boundary=----WebAppBoundary

------WebAppBoundary
Content-Disposition: form-data; name="category"

Gatebook
------WebAppBoundary
Content-Disposition: form-data; name="name"

GATE Electrical Engineering 2025 (Arihant Experts)
------WebAppBoundary
Content-Disposition: form-data; name="rentalCostPerDay"

15
------WebAppBoundary
Content-Disposition: form-data; name="collectionPlace"

College Library
------WebAppBoundary
Content-Disposition: form-data; name="contactPhoneNumber"

9492781864
------WebAppBoundary
Content-Disposition: form-data; name="proofRequired"

college id card copy 
------WebAppBoundary
Content-Disposition: form-data; name="securityDeposit"

150
------WebAppBoundary
Content-Disposition: form-data; name="edition"

2025
------WebAppBoundary
# IMPORTANT: You MUST replace the path below with a real path to an image on your computer.
Content-Disposition: form-data; name="imageUrl"; filename="book.jpg"
Content-Type: image/jpeg

< C:\ResumeFolder\resume folder\vaagdeviProjectimages\g-5.jpg
------WebAppBoundary--

### 

### =================================
### POST A NEW CALCULATOR
### =================================

### Create a New Calculator
POST http://localhost:3001/api/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU0NTcwMzQyLCJleHAiOjE3NTcxNjIzNDJ9.I9Md-D-c6U03dkkO_8l3JdQuqgq1Z7_NeoC-J1ZvZyY
Content-Type: multipart/form-data; boundary=----WebAppBoundary

------WebAppBoundary
Content-Disposition: form-data; name="category"

Calculator
------WebAppBoundary
Content-Disposition: form-data; name="name"

Texas Instruments TI-36X Pro
------WebAppBoundary
Content-Disposition: form-data; name="rentalCostPerDay"

20
------WebAppBoundary
Content-Disposition: form-data; name="collectionPlace"

First Year Block
------WebAppBoundary
Content-Disposition: form-data; name="contactPhoneNumber"

9492781864
------WebAppBoundary
Content-Disposition: form-data; name="proofRequired"

College ID Card copy 
------WebAppBoundary
Content-Disposition: form-data; name="securityDeposit"

150
------WebAppBoundary
Content-Disposition: form-data; name="model"

MultiView Scientific Calculator
------WebAppBoundary
# IMPORTANT: You MUST replace the path below with a real path to an image on your computer.
Content-Disposition: form-data; name="imageUrl"; filename="calculator.jpg"
Content-Type: image/jpeg

< C:\ResumeFolder\resume folder\vaagdeviProjectimages\c-3.webp
------WebAppBoundary--

####
GET http://localhost:3001/api/products/gatebooks


### Get All Drafters
GET http://localhost:3001/api/products/drafters

###

GET  http://localhost:3001/api/products/laptops 

### 
GET http://localhost:3001/api/products/cameras

### Update the details for the Camera with ID 4
PUT http://localhost:3001/api/products/camera/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU0NTcwMzQyLCJleHAiOjE3NTcxNjIzNDJ9.I9Md-D-c6U03dkkO_8l3JdQuqgq1Z7_NeoC-J1ZvZyY

{
    "model": "compact", 
    "storage": "8GB SD Card"
}

### 

PUT http://localhost:3001/api/products/laptop/7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU0NTcxNzg5LCJleHAiOjE3NTcxNjM3ODl9.PCawbsBeaK6m2VuMwLB-6L3RPMw8KTjwNdxGMjdVOi4

{
    "rentalCostPerDay": 100,
    "inStock": true,
    "collectionPlace": "college main gate" , 
}

### 

DELETE http://localhost:3001/api/products/laptop/10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU0NTcwMzQyLCJleHAiOjE3NTcxNjIzNDJ9.I9Md-D-c6U03dkkO_8l3JdQuqgq1Z7_NeoC-J1ZvZyY


### 

GET http://localhost:3001/api/products/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzU0ODExMjgxLCJleHAiOjE3NTc0MDMyODF9.FLV9sIF6uANeusmQd9S0_jx7FK4bqZpAVGZ4wEMMSIk 

### 

GET http://localhost:3001/api/products/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzU0ODExMjgxLCJleHAiOjE3NTc0MDMyODF9.FLV9sIF6uANeusmQd9S0_jx7FK4bqZpAVGZ4wEMMSIk 


### 

POST http://localhost:3001/api/rentals
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzU0ODEzMTgxLCJleHAiOjE3NTc0MDUxODF9.jR45juUmpvQiIbH_e8J2cud9IQo3c2pogtOCab5WHVY

{
  "productCategory": "Laptop",
  "productId": 2,
  "startDate": "2025-09-10",
  "endDate": "2025-09-15"
}

### 

### OWNER marks their notifications as read
PATCH http://localhost:3001/api/notifications/mark-as-read
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzU0ODEzMTgxLCJleHAiOjE3NTc0MDUxODF9.jR45juUmpvQiIbH_e8J2cud9IQo3c2pogtOCab5WHVY




### 

PATCH http://localhost:3001/api/rentals/2/status
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU0ODEzNzYxLCJleHAiOjE3NTc0MDU3NjF9.p582Rfg7fBltGxwsj5UCGFYuiWZmKg1AgEJIzET7CC4

{
    "status": "non-active"
}

### RENTER checks their notifications
# They should see a new notification that their request was approved.
GET http://localhost:3001/api/notifications
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzU0ODEzODUzLCJleHAiOjE3NTc0MDU4NTN9.deAkiCPpz0j_PAr9YryBBHQhGgocKO-H6P3t94MoWLk


### RENTER checks their "My Rentals" list
# The status of the rental should now be "active".
GET http://localhost:3001/api/rentals/my-rentals
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzU0NTY4NjIzLCJleHAiOjE3NTcxNjA2MjN9.H1FUzipwwf0VmhmfNDnZannr9AlDzvlNqhLcNhERGx8 

###

### OWNER checks their listings to see only 'active' rentals
GET http://localhost:3001/api/rentals/my-listings?status=active
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU0ODE1NDIyLCJleHAiOjE3NTc0MDc0MjJ9.hsGtcmWkE7gFRoxClGeyJAviLaXI0R-jlAf03tCQfoc
